-- ============================================================
-- DB2 Schema for AI Data Validation System
-- Database: DATAVAL
-- ============================================================

-- Table: DATASET_RUN
-- Stores metadata for each validation run
CREATE TABLE DATASET_RUN (
    RUN_ID        INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY,
    DOMAIN        VARCHAR(20)   NOT NULL,
    FILE_NAME     VARCHAR(255)  NOT NULL,
    TOTAL_RECORDS INTEGER       DEFAULT 0,
    VALID_COUNT   INTEGER       DEFAULT 0,
    INVALID_COUNT INTEGER       DEFAULT 0,
    SCORE         DECIMAL(5,2)  DEFAULT 0.00,
    RUN_DATE      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    STATUS        VARCHAR(20)   DEFAULT 'PENDING',
    PRIMARY KEY (RUN_ID)
);

-- Table: VALID_RECORDS
-- Stores individual records that passed validation
CREATE TABLE VALID_RECORDS (
    RECORD_ID   INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY,
    RUN_ID      INTEGER       NOT NULL,
    RECORD_DATA VARCHAR(2000) NOT NULL,
    PRIMARY KEY (RECORD_ID),
    FOREIGN KEY (RUN_ID) REFERENCES DATASET_RUN(RUN_ID)
        ON DELETE CASCADE
);

-- Table: ERROR_RECORDS
-- Stores individual records that failed validation with error info
CREATE TABLE ERROR_RECORDS (
    ERROR_ID    INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY,
    RUN_ID      INTEGER       NOT NULL,
    RECORD_DATA VARCHAR(2000) NOT NULL,
    ERROR_MSG   VARCHAR(500)  NOT NULL,
    PRIMARY KEY (ERROR_ID),
    FOREIGN KEY (RUN_ID) REFERENCES DATASET_RUN(RUN_ID)
        ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX IDX_RUN_DOMAIN ON DATASET_RUN(DOMAIN);
CREATE INDEX IDX_RUN_DATE ON DATASET_RUN(RUN_DATE);
CREATE INDEX IDX_VALID_RUNID ON VALID_RECORDS(RUN_ID);
CREATE INDEX IDX_ERROR_RUNID ON ERROR_RECORDS(RUN_ID);
